/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rmiteste1;

import rmiteste1.Servico;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmiteste2.Servico2;

/**
 *
 * @author DELL-Fabio
 */
public class Cliente extends javax.swing.JDialog {
    Servico servico = null;
    Servico2 servico2 = null;
    /**
     * Creates new form Cliente
     * @param parent
     */
    public Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                
        try {
            Registry registry = LocateRegistry.getRegistry("172.16.102.16",12345);
            servico = (Servico) registry.lookup("TesteFabio");
            //servico = (Servico) Naming.lookup(localizacao);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro " + ex.getMessage());
        }
        
        try {
            Registry registry = LocateRegistry.getRegistry("172.16.102.16",8080);
            servico2 = (Servico2) registry.lookup("TesteLucas");
            //servico = (Servico) Naming.lookup(localizacao);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro " + ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNome = new javax.swing.JTextField();
        btnConecta = new javax.swing.JButton();
        btnMostrarSaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRealizarSaque = new javax.swing.JButton();
        btnRealizarDeposito = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtValorSaque = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtValorDeposito = new javax.swing.JTextField();
        btnGoSaque = new javax.swing.JButton();
        btnGoDeposito = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        btnTrocarUsuario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnConecta.setText("Conectar");
        btnConecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectaActionPerformed(evt);
            }
        });

        btnMostrarSaldo.setText("Mostrar Saldo");
        btnMostrarSaldo.setEnabled(false);
        btnMostrarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarSaldoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Senha:");

        btnRealizarSaque.setText("Realizar Saque");
        btnRealizarSaque.setEnabled(false);
        btnRealizarSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarSaqueActionPerformed(evt);
            }
        });

        btnRealizarDeposito.setText("Realizar Depósito");
        btnRealizarDeposito.setEnabled(false);
        btnRealizarDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarDepositoActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor para saque:");

        txtValorSaque.setEnabled(false);

        jLabel4.setText("Valor para depósito:");

        txtValorDeposito.setEnabled(false);

        btnGoSaque.setText("Go!");
        btnGoSaque.setEnabled(false);
        btnGoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoSaqueActionPerformed(evt);
            }
        });

        btnGoDeposito.setText("Go!");
        btnGoDeposito.setEnabled(false);
        btnGoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoDepositoActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnTrocarUsuario.setText("Trocar Usuário");
        btnTrocarUsuario.setEnabled(false);
        btnTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrocarUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Agencia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarSaldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConecta, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(btnRealizarSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRealizarDeposito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(txtSenha)))
                    .addComponent(btnTrocarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtValorSaque, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(txtValorDeposito))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnGoSaque)
                                .addComponent(btnGoDeposito))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(29, 29, 29)
                            .addComponent(txtAgencia))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConecta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarSaque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRealizarDeposito)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnGoSaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnGoDeposito))
                .addGap(27, 27, 27)
                .addComponent(btnTrocarUsuario)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectaActionPerformed
        // TODO add your handling code here:
        /*
        try {
            // TODO add your handling code here:
            JOptionPane.showMessageDialog(null,"Hora do Servidor: " + servico.getDataHora());
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        */
        txtValorSaque.setEnabled(false);
        btnGoSaque.setEnabled(false);
                
        txtValorDeposito.setEnabled(false);
        btnGoDeposito.setEnabled(false);
        boolean teste = false;
        try {
            teste = servico.ConectaBanco(txtNome.getText(), txtSenha.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (teste)
        {
            JOptionPane.showMessageDialog(null, "Conectado");
            btnMostrarSaldo.setEnabled(true);
            btnRealizarDeposito.setEnabled(true);
            btnRealizarSaque.setEnabled(true);
            btnConecta.setEnabled(false);
            txtNome.setEnabled(false);
            txtSenha.setEnabled(false);
            btnTrocarUsuario.setEnabled(true);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "erro no login");
        }
        
    }//GEN-LAST:event_btnConectaActionPerformed

    private void btnMostrarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarSaldoActionPerformed
        txtValorSaque.setEnabled(false);
        btnGoSaque.setEnabled(false);
        txtValorDeposito.setEnabled(false);
        btnGoDeposito.setEnabled(false);
        double teste = 0;
        try {
            teste = servico.Saldo(txtNome.getText(), txtSenha.getText());
        } catch (RemoteException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Saldo: R$ " + Double.toString(teste));

        
        
    }//GEN-LAST:event_btnMostrarSaldoActionPerformed

    private void btnRealizarSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarSaqueActionPerformed
        txtValorSaque.setEnabled(true);
        btnGoSaque.setEnabled(true);  
        txtValorDeposito.setEnabled(false);
        btnGoDeposito.setEnabled(false);

        
    }//GEN-LAST:event_btnRealizarSaqueActionPerformed

    private void btnRealizarDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarDepositoActionPerformed
        txtValorSaque.setEnabled(false);
        btnGoSaque.setEnabled(false);  
        
        btnGoDeposito.setEnabled(true);
        txtValorDeposito.setEnabled(true);
    }//GEN-LAST:event_btnRealizarDepositoActionPerformed

    private void btnGoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoSaqueActionPerformed
        double valorSaque = Double.parseDouble(txtValorSaque.getText());
        double teste1 = 0;
        double teste2 = 0;
        if(txtAgencia.getText()=="1"){
            try {
                teste1 = servico.Saldo(txtNome.getText(), txtSenha.getText()) - valorSaque;
                if(teste1 >= 0){
                    teste2 = servico.atualizarSaldo(txtNome.getText(), txtSenha.getText(), teste1);
                    JOptionPane.showMessageDialog(null, "Saque realizado com sucesso! Saldo atualizado: R$ " + Double.toString(teste1));
                }else{
                    JOptionPane.showMessageDialog(null, "ERRO! Saldo insuficiente!");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtValorSaque.setText("");
            txtValorDeposito.setText("");
        }else{
            try {
                teste1 = servico2.Saldo(txtNome.getText(), txtSenha.getText()) - valorSaque;
                if(teste1 >= 0){
                    teste2 = servico2.atualizarSaldo(txtNome.getText(), txtSenha.getText(), teste1);
                    JOptionPane.showMessageDialog(null, "Saque realizado com sucesso! Saldo atualizado: R$ " + Double.toString(teste1));
                }else{
                    JOptionPane.showMessageDialog(null, "ERRO! Saldo insuficiente!");
                }
            } catch (RemoteException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            txtValorSaque.setText("");
            txtValorDeposito.setText("");
        }
    }//GEN-LAST:event_btnGoSaqueActionPerformed

    private void btnGoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoDepositoActionPerformed
        double valorDeposito = Double.parseDouble(txtValorDeposito.getText());
        double teste1 = 0;
        double teste2 = 0;        
        try {
            teste1 = servico.Saldo(txtNome.getText(), txtSenha.getText()) + valorDeposito;
            teste2 = servico.atualizarSaldo(txtNome.getText(), txtSenha.getText(), teste1);
        } catch (RemoteException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(teste1 >= 0){
            JOptionPane.showMessageDialog(null, "Depósito realizado com sucesso!");
        }
        txtValorSaque.setText("");
        txtValorDeposito.setText("");        
    }//GEN-LAST:event_btnGoDepositoActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        txtSenha.setEchoChar((char)0);
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrocarUsuarioActionPerformed
        btnMostrarSaldo.setEnabled(false);
        btnRealizarDeposito.setEnabled(false);
        btnRealizarSaque.setEnabled(false);
        btnConecta.setEnabled(true);
        txtNome.setEnabled(true);
        txtSenha.setEnabled(true);
        btnTrocarUsuario.setEnabled(false);
        txtValorSaque.setEnabled(false);
        btnGoSaque.setEnabled(false);
        btnGoDeposito.setEnabled(false);
        txtValorDeposito.setEnabled(false);
    }//GEN-LAST:event_btnTrocarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente dialog = new Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConecta;
    private javax.swing.JButton btnGoDeposito;
    private javax.swing.JButton btnGoSaque;
    private javax.swing.JButton btnMostrarSaldo;
    private javax.swing.JButton btnRealizarDeposito;
    private javax.swing.JButton btnRealizarSaque;
    private javax.swing.JButton btnTrocarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtValorDeposito;
    private javax.swing.JTextField txtValorSaque;
    // End of variables declaration//GEN-END:variables
}
